spring.application.name=ImageDatabaseDemo

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ImageDemo_db
spring.datasource.username=root
spring.datasource.password=Sagar@112455
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

