spring.application.name=Spring-Boot-logging

#logging.level.root=DEBUG

#logging.level.com.sagar.Spring_Boot_logging.services = DEBUG;

#logging.level.com.sagar.Spring_Boot_logging.controller = INFO;

#logging.file.name= logs/app.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
