spring.application.name=SpringOauth2Demo

spring.security.oauth2.client.registration.google.client-id=YOUR_REAL_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_REAL_CLIENT_SECRET

#for Github
spring.security.oauth2.client.registration.github.client-id=YOUR_REAL_CLIENT_ID
spring.security.oauth2.client.registration.github.client-secret=YOUR_REAL_CLIENT_SECRET